//
//  Biome.hpp
//  Biome
//
//  Created by Logan Smith on 5/14/16.
//
//

#ifndef Biome_hpp
#define Biome_hpp

#include <vector>

/** @class Biome
 @brief A data structure representing a biome.  Tightly coupled with BiomeManager, which you should prefer to interact with.
 
 A biome has information about its atmosphere (fog information) and the sprites that its scenery can choose from.  In the future, more information will be added to this structure.  Ideas:
 - sky information
 - different 'classes' of scenery: foreground, background, etc.
 - creatures present
 - terrain colors/textures
 
 A biome might be predefined or randomly generated by BiomeManager.
 
 */
struct Biome {
public:
    friend class BiomeManager;
    
    /** @class FogInfo
     @brief Helper struct containing information about the fog in a biome.
     */
    struct FogInfo {
        cocos2d::Color4F color;
        float thickness;
        FogInfo( cocos2d::Color4F color = cocos2d::Color4F::WHITE, float thickness = 1.f )
        :   color( color ),
        thickness( thickness )
        {}
    };
    
    /**
     Creates a biome with the given fog info, if any, and the given list of available sprites to use, if any.
     */
    Biome( FogInfo fogInfo = FogInfo(), std::vector<std::string> scenerySprites = std::vector<std::string>() );
    
    /**
     Creates a biome with the sprites "rock.png" and "tree.png" from the given folder path (for convenience in testing), as well as the given fog info, if any.
     */
    Biome( std::string folderPath, FogInfo fogInfo = FogInfo() );
    
    /**
     Get a vector listing the current sprites that can be chosen by scenery.
     */
    const std::vector<std::string>& getScenerySprites() const {
        return scenerySprites;
    }
    /**
     Get the fog color of this biome.
     */
    const cocos2d::Color4F& getFogColor() const {
        return fogInfo.color;
    }
    /**
     Get the fog thickness of this biome.
     */
    const float getFogThickness() const {
        return fogInfo.thickness;
    }
    /**
     Get the Biome::FogInfo struct that this biome owns.
     */
    const FogInfo& getFogInfo() const {
        return this->fogInfo;
    }
    
private:
    std::vector<std::string> scenerySprites;
    FogInfo fogInfo;
};

#endif /* Biome_hpp */
