//
//  TerrainChunk.hpp
//  Biome
//
//  Created by Logan Smith on 5/15/16.
//
//

#ifndef TerrainChunk_hpp
#define TerrainChunk_hpp

#include "cocos2d.h"

/** @class TerrainChunk
 @brief A TerrainChunk is a node generated by a `TerrainGenerator` instance that represents terrain.  It handles the custom drawing of the terrain.  TerrainChunk instances are the "building blocks" managed by TerrainLayer instances, and are scrolled past in a (hopefully) seamless fashion to create the effect of an endless, seamless terrain.
 */
class TerrainChunk : public cocos2d::Layer {
public:
    friend class TerrainGenerator;
    friend class TerrainLayer;
    CREATE_FUNC(TerrainChunk);
    bool init() override;
    
    virtual void draw(cocos2d::Renderer* renderer, const cocos2d::Mat4& transform, uint32_t flags) override;

private:
    /**
     * Used internally by TerrainLayer to find the height at a given x coordinate.  x is given in terms of the chunk's nodeContainer.
     */
    float getHeightForAbsoluteXCoordinate( float x );
    std::vector<cocos2d::Vec2> points;
    cocos2d::CustomCommand _customCmd;
    void onDraw( const cocos2d::Mat4 &transform, uint32_t flags);
    
    cocos2d::Color4F _DEBUGGING_ONLY_lineColor; ///< for debugging only.  choose a random line color for this terrain, to easily see the separation of different chunks.
};

#endif /* TerrainChunk_hpp */
